* Test of Org-mode document export to Github markdown
#+AUTHOR: Dmytro Bevzenko
#+EXPORT_EXCLUDE_TAGS: noexport
Using =ox-gfm= module.
** No export section                                               :noexport:
This section should not be exported.
** Another section
But I must explain to you how all this mistaken idea of denouncing of a pleasure and praising pain was born and I will
give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the
master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but
because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor
again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but occasionally
circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us
ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find
fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that
produces no resultant pleasure? [33] On the other hand, we denounce with righteous indignation and dislike men who are
so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the
pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of
will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to
distinguish. In a free hour, when our power of choice is untrammeled and when nothing prevents our being able to do what
we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the
claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and
annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects
pleasures to secure other greater pleasures, or else he endures pains to avoid worse.
** Styling
1. /This text is italic/
2. *This text is bold*
3. _This text is underlined_
4. =This text is verbatim=
5. ~const a = foo(b);~
6. +This text is strike-through+
** Code blocks
The following is a code block writen in Typescript:
#+name: block1
#+begin_src 
const a = 10;

function square(x: number) {
  return x*x;
}
#+end_src
** More text 
But I must explain to you how all this mistaken idea of denouncing of a pleasure and praising pain was born and I will
give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the
master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but
because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor
again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but occasionally
circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us
ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find
fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that
produces no resultant pleasure? [33] On the other hand, we denounce with righteous indignation and dislike men who are
so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the
pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of
will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to
distinguish. In a free hour, when our power of choice is untrammeled and when nothing prevents our being able to do what
we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the
claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and
annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects
pleasures to secure other greater pleasures, or else he endures pains to avoid worse.

But I must explain to you how all this mistaken idea of denouncing of a pleasure and praising pain was born and I will
give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the
master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but
because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor
again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but occasionally
circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us
ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find
fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that
produces no resultant pleasure? [33] On the other hand, we denounce with righteous indignation and dislike men who are
so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the
pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of
will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to
distinguish. In a free hour, when our power of choice is untrammeled and when nothing prevents our being able to do what
we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the
claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and
annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects
pleasures to secure other greater pleasures, or else he endures pains to avoid worse.

But I must explain to you how all this mistaken idea of denouncing of a pleasure and praising pain was born and I will
give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the
master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but
because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor
again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but occasionally
circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us
ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find
fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that
produces no resultant pleasure? [33] On the other hand, we denounce with righteous indignation and dislike men who are
so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the
pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of
will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to
distinguish. In a free hour, when our power of choice is untrammeled and when nothing prevents our being able to do what
we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the
claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and
annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects
pleasures to secure other greater pleasures, or else he endures pains to avoid worse.
